name: Changelog

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # compareLink: false
          issuesLabel: "**Issues**"
          enhancementLabel: "**Enhancements**"
          prLabel: "**Pull Requests**"
